[package]
name = "steamworks-encrypted-app-ticket"
version = "0.1.0"
edition = "2024"

[dependencies]
steamworks-encrypted-app-ticket-sys = { path = "../steamworks-encrypted-app-ticket-sys" }
thiserror = "2.0.17"

[dev-dependencies]
hex = "0.4.3"